services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITLAB_DEPLOY_TOKEN: ${GITLAB_DEPLOY_TOKEN}
        GITLAB_REPO_URL: ${GITLAB_REPO_URL}
    volumes:
      - nginx_config:/tmp/nginx.conf
    networks:
      - app-network

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - nginx_config:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

volumes:
  nginx_config:
    driver: local

networks:
  app-network:
    driver: bridge
